server:
  port: 8765
  # Forward headers to services
  forward-headers-strategy: framework

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # For testing only
  security:
    enabled: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # Let Gateway discover routes via discovery service (Eureka registry)
          enabled: true
          lowerCaseServiceId: true