eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    # Client will store local copy of registry info (for load balancing on the client side)
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/