eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ostock_db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:7080/realms/organizations-realm
          # to start it independently
          jwk-set-uri: http://keycloak:7080/realms/organizations-realm/protocol/openid-connect/certs