spring:
  application:
    name: eureka-server
  config:
    import: 'optional:configserver:'
  cloud:
      config:
        uri: http://config-server:8888
      loadbalancer:
        ribbon:
          enabled: false