spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ostock_db
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false