spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

test:
  property: "Value of the test property for comment"

scheduler:
  interval:
    millis: 30000