management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

test:
  property: Hello world!